<?php
/** @generate-function-entries */

/* This file is generated by the 'xdebug.org:html/docs/create-stubs.php' robot
 * for Xdebug 3.1.0-dev — do not modify by hand */

/* Emits a breakpoint to the debug client */
function xdebug_break(): bool {}

/* -----------------------------------------------------------------------*/

/* Instructs Xdebug to establish a debugging session */
function xdebug_connect_to_client(): bool {}

/* -----------------------------------------------------------------------*/

/* Show and retrieve diagnostic information */
/** @return mixed */
function xdebug_info(?string $category = null) {}

/* -----------------------------------------------------------------------*/

/* Returns whether a debugging session is active */
function xdebug_is_debugger_active(): bool {}

/* -----------------------------------------------------------------------*/

/* Sends data to a debugging client */
function xdebug_notify(mixed $data): bool {}

/* -----------------------------------------------------------------------*/
