; Needed so that the php scripts won't time out while being run
max_execution_time=0
; We remove all error handling, printing, and displaying so that it does not
; interfere with the tests
error_reporting=0
display_errors=off
log_errors=off
