zend_extension=php_debugger.so
php_debugger.start_with_request=no
; We need this because some of the functions in bench.php do deep recursion and the default nesting level is not enough
php_debugger.max_nesting_level=2048
